
/*
 * Generated by XDoclet - Do not edit!
 */
package com.sapienter.jbilling.server.entity;

/**
 * Value object for PaymentInfoCashDTO entity.
 *
 * @author Pavlo Maksymchuk
 */
public class PaymentInfoCashDTO extends java.lang.Object implements java.io.Serializable {

    private java.lang.Integer id;
    private boolean idHasBeenSet = false;
    private java.lang.String customerRef;
    private boolean customerRefHasBeenSet = false;
    private java.util.Date date;
    private boolean dateHasBeenSet = false;
    private java.lang.Integer pk;

    public PaymentInfoCashDTO() {
    }

    public PaymentInfoCashDTO(java.lang.Integer id, java.lang.String customerRef, java.util.Date date) {
        this.id = id;
        idHasBeenSet = true;
        this.customerRef = customerRef;
        customerRefHasBeenSet = true;
        this.date = date;
        dateHasBeenSet = true;
        pk = this.getId();
    }

    //TODO Cloneable is better than this !
    public PaymentInfoCashDTO(PaymentInfoCashDTO otherValue) {
        this.id = otherValue.id;
        idHasBeenSet = true;
        this.customerRef = otherValue.customerRef;
        customerRefHasBeenSet = true;
        this.date = otherValue.date;
        dateHasBeenSet = true;

        pk = this.getId();
    }

    public java.lang.Integer getPrimaryKey() {
        return pk;
    }

    public void setPrimaryKey(java.lang.Integer pk) {
        // it's also nice to update PK object - just in case
        // somebody would ask for it later...
        this.pk = pk;
        setId(pk);
    }

    public java.lang.Integer getId() {
        return this.id;
    }

    public void setId(java.lang.Integer id) {
        this.id = id;
        idHasBeenSet = true;

        pk = id;
    }

    public boolean idHasBeenSet() {
        return idHasBeenSet;
    }

    public java.lang.String getCustomerRef() {
        return this.customerRef;
    }

    public void setCustomerRef(java.lang.String customerRef) {
        this.customerRef = customerRef;
        customerRefHasBeenSet = true;

    }

    public boolean customerRefHasBeenSet() {
        return customerRefHasBeenSet;
    }

    public java.util.Date getDate() {
        return this.date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
        dateHasBeenSet = true;

    }

    public boolean dateHasBeenSet() {
        return dateHasBeenSet;
    }

    public String toString() {
        StringBuilder str = new StringBuilder("{");

        str.append("id=").append(getId()).append(" " + " " + "ref=").append(getCustomerRef()).append(" " + "date=").append(getDate());
        str.append('}');

        return (str.toString());
    }

    /**
     * A Value Object has an identity if the attributes making its Primary Key
     * have all been set. An object without identity is never equal to any other
     * object.
     *
     * @return true if this instance has an identity.
     */
    protected boolean hasIdentity() {
        return idHasBeenSet;
    }

    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!hasIdentity()) {
            return false;
        }
        if (other instanceof PaymentInfoCashDTO) {
            PaymentInfoCashDTO that = (PaymentInfoCashDTO) other;
            if (!that.hasIdentity()) {
                return false;
            }
            boolean lEquals = true;
            if (this.id == null) {
                lEquals = lEquals && (that.id == null);
            } else {
                lEquals = lEquals && this.id.equals(that.id);
            }

            lEquals = lEquals && isIdentical(that);

            return lEquals;
        } else {
            return false;
        }
    }

    public boolean isIdentical(Object other) {
        if (other instanceof PaymentInfoCashDTO) {
            PaymentInfoCashDTO that = (PaymentInfoCashDTO) other;
            boolean lEquals = true;
            if (this.customerRef == null) {
                lEquals = lEquals && (that.customerRef == null);
            } else {
                lEquals = lEquals && this.customerRef.equals(that.customerRef);
            }
            if (this.date == null) {
                lEquals = lEquals && (that.date == null);
            } else {
                lEquals = lEquals && this.date.equals(that.date);
            }

            return lEquals;
        } else {
            return false;
        }
    }

    public int hashCode() {
        int result = 17;
        result = 37 * result + ((this.id != null) ? this.id.hashCode() : 0);
        result = 37 * result + ((this.customerRef != null) ? this.customerRef.hashCode() : 0);
        result = 37 * result + ((this.date != null) ? this.date.hashCode() : 0);

        return result;
    }
}
